Repository Cyntax-Inc/cyntax.org, pull requests merged in 2025-06, with the labels that each got.

#1 Feature/init app
  .github/workflows/prod.yml
  LICENSE
  README.md
Labels: documentation, enhancement, good first issue

#3 QA => PROD (MAIIN)
  .github/workflows/prod.yml
  LICENSE
  README.md
Labels: documentation, enhancement, good first issue

#6 Add github link
  components/Footer/index.tsx
Labels: update

#8 TEST => QA
  app/(site)/head.tsx
  app/favicon.ico
  components/Footer/index.tsx
Labels: bug, update

#14 Added socials in contact form
  components/Common/SocialIcons.tsx
  components/Contact/index.tsx
Labels: enhancement, good first issue
